### PR TITLE
[WIP] Reworded num_channels portion and mentioned Collections

### PR DESCRIPTION
**Pull request by 777arc**
Reworded num_channels to make it clear it was intended for real signals and Collections are intended for multiple channels of complex signals, it has proven to be an area of confusion and most importantly we don't want folks to assume num_channels is *the* way to capture multiple RF channels off a receiver.

### CODE REVIEW

**Comment by gmabey** [comment]
Hrm -- I used a RF receiver once that produced multi-channel packets of complex data. Seems like a very efficient way to implement beam forming algorithms: you've got all of the channels right there, and time synchronized.

Why not allow multi-channel complex recordings? Is the only motivation to prevent users from getting confused? Or, is utility and efficiency a higher, nobler way? For a user fluent in numpy N-D-isms, seems like N=2, dtype=complex32 isn't really a stretch.

Why do you say that `num_channels` isn't the "proper" way to capture multiple RF channels off a receiver?  What is improper about it?  How then is storing multiple channels of real samples proper?

I certainly have encountered the case where channels were not necessarily time synchronized, and I *thought* that a collection would very nicely cover that case.

I myself really appreciate the potential to store multiple channels of complex data with a single time stamp.

**Comment by 777arc** [comment]
Didn't use the word proper, but the point here is to make sure folks dont read the spec and assume that num_channels is the way to represent multiple rx channels.  In the end its a tradeoff between the number of files you have to deal with, and ease of ingesting the files into other software.  It's not hard to deinterleave, but for a lot of folks its going to be the difference between being able to directly use certain software to analyze their recordings and not.

**Comment by gmabey** [comment]
I apologize -- I thought for sure I saw the word "proper" in your comment somewhere.

So, the motivation for this proposed change is ... compatibility?  That is, to make it more likely for software that ignores the `num_channels` quantity to use data in a recording?

**Comment by 777arc** [comment]
Yeah pretty much, even though right now there's not a ton of tooling around SigMF, over time there will be more, and some fraction isn't going to support num_channels (since it was intended for real-valued signals like audio and DAQs anyway)

**Comment by 777arc** [comment]
Also if I step back and think about examples of RF recordings that have multiple channels, what comes to mind is stuff like multi-element arrays, and satellite ground stations where you get H and V polarizations.  So Sentinel 1 for example releases their raw RF signals to the world and they have H and V as separate files.  For multi-element arrays you're going to be doing some form of MIMO DSP and its likely a custom piece of software.

**Comment by jacobagilbert** [comment]
I'd like a few wording tweaks here @777arc - I don't think it is right to recommend either format for multichannel real valued systems; the best format is going to depend on the application.


> **_When_** representing multiple channels of **_complex valued data_** that **_are related, such as multiple channels of IQ data_**, the Collections format is recommended. **_When representing_** real-valued recordings that contain more than one channel, **_such as from a multichannel data acquisition device, using the interleaved multichannel format and the_** `core:num_channels` field in the Global Object (described below) **_may be more appropriate._**

Let me know what you think.

**Comment by 777arc** [comment]
Great suggestion, I've updated the paragraph.  Do we want to still include that L/R example at the end or should we go deeper into num_channels related stuff further down the doc?

**Comment by gmabey** [comment]
I do like this new version "better" but I'm still surprised that there's interest in differentiating between real values and complex values.  What's so different about them that warrants saying anything at all? "A shorter spec is a better spec." -- *attributed to Cicero, circa 75 BC* LOL

**Comment by jacobagilbert** [comment]
The point of this recommendation (as I see it) is to encourage compatibility with tools like Inspectrum and IQEngine. SigMF was created with the intent of managing raw IQ recordings from radios, and that remains the focus; "a binary file of IQ or RF samples" is the only example in our readme for a reason. Suggestions also get to the point of "make it easy to use" which is a stated objective -- less pain means a better user experience.

> A shorter spec is a better spec.

I definitely agree with this, but there is a rule that supersedes that one:

> A good spec provides exactly one way to accomplish something

And because that is not always possible, I think recommendations like this are suitable.

**Comment by jacobagilbert** [comment]
I don't care too much for the recent edits and I would like to revisit the original point of this:

Its not obvious how one should store multichannel complex valued data in SigMF, and almost every tool that exists to manipulate such data (inspectrum, baudline, gnuradio, UHD, soapy, iq_engine, sceptre, spike, gqrx, hdsdr, sdrangel, countless govt tools, etc etc) accept IQ data per-channel. SigMF should, since we don't hate our users and want to make their lives easier, direct new people toward **Collections** for this use case.

Nothing about this would _prevent_ or stop anyone from implementing this however they see fit, and there are some niche reasons to use single-file recordings. This is merely intended to help people who otherwise don't know to do this in the standard way.

**Pull request closed without merging**
